---
title: "Fst with multidimiensional scaling"
author: "Makar Dorohuntsev"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,fig.width = 11)
```

### 1. Creating Fst from genind

Read previously filtered VCF file to R and select most frequent SNP per marker. Next create genind with set populations and group them using seppop() to make list of geninds by populations.

```{r}
library(vcfR)
library(pegas)
library(graph4lg)
library(stats)
library(dplyr)
# load file with population names 
load("~/Library/CloudStorage/Dropbox/Salamandra project/sorted_BAM/pop name.RData")
# snps - Large vcfR data file
load("~/Desktop/Data do projektu/Data/id by mafs.RData")
load("~/Library/CloudStorage/Dropbox/Salamandra project/sorted_BAM/SNP names.RData")
snps <- vcfR::read.vcfR("~/Library/CloudStorage/Dropbox/Salamandra project/sorted_BAM/final.vcf", convertNA  = TRUE)
# read row snps from vcf file, transpose and create loci 
row_vcf <- as.loci(t(vcfR::extract.gt(snps, 
                             element = "GT",
                             IDtoRowNames  = T,
                             as.numeric = F,
                             convertNA = F,
                             return.alleles = T)))
#filter loci 
filtred_loci <- row_vcf %>% select(c(unlist(filtred_id)))
colnames(filtred_loci) <- c(unlist(filtred_id))
# convert loci to genind
test_genind <- loci2genind(filtred_loci)
# add population data to genind
test_genind@pop <- as.factor(c(a))

Fst <- mat_pw_fst(test_genind)
#multidimentional scaling from Fst
fit <- cmdscale(Fst, eig=TRUE, k=2)
```

### 2. Create plot from Fst

After multidimensional scaling create scatter plot to show the fixation indexes of populations

```{r}
#extract (x, y) coordinates of multidimensional scaling
x <- fit$points[,1]
y <- fit$points[,2]
#create scatter plot
plot(x, y, xlab="Dimension 1", ylab="Dimension 2",
     main="Multidimensional Scaling Results", type="n")
abline(v=(seq(0,100,25)), col="lightgray", lty="dotted")
abline(h=(seq(0,100,25)), col="lightgray", lty="dotted")
par(new=TRUE)
#add row names of data frame as labels
text(x, y, labels=row.names(Fst))
```
